c_stdlib_version:          # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
# According to
# https://github.com/golang/go/issues/75013
# https://github.com/NixOS/nixpkgs/issues/433688
# our go toolchain now requires macos 12+
MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx and x86_64]
  - '12.3'                 # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '12.3'                 # [osx and x86_64]
  - '12.3'                 # [osx and arm64]
